title: Default Page

status:
  draft: Draft
  listed: Published

columns:
  main:
    width: 2/3
    sections:
      fields:
        type: fields
        fields:
          text:
            type: textarea
            size: huge
  sidebar:
    width: 1/3
    sections:
      extra:
        type: fields
        fields:
          number:
            label:
              en: Number
              de: Nummer
            type: number
            translate: false
      pages:
        type: pages
        label:
          en: Articles
          de: Artikel
        template: default
      files:
        type: files
