name: Deploy New Estate Nuanu

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Deploying Backend changes
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.DEV_HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.DEV_SSH_KEY }}
        script: |
            sudo su
            whoami
            sleep 5
            cd /var/www/html/new-nuanu
            ls -alh
            git config --global --add safe.directory /var/www/html/new-nuanu
            sleep 5
            if [[ $(git status --porcelain | wc -l) -gt 0 ]]; then   
                echo "New Update Found - Processing git command push and pull" 
                sudo git add .
                sleep 5
                sudo git commit -m [UPDATE]From server
                sleep 5
                sudo git pull origin main
                sleep 10
            else 
                echo "No Update Found"
                sudo git pull origin main
                sleep 10
            fi
            sudo systemctl restart nginx

    - name: Deploying Front end changes
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.DEV_HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.DEV_SSH_KEY }}
        script: |
            sudo su
            cd new-estate-nuanu/
            ls -alh
            git config --global --add safe.directory new-estate-nuanu/
            if [[ $(git status --porcelain | wc -l) -gt 0 ]]; then   
                echo "New Update Found - Processing git command push and pull" 
                sudo git add .
                sleep 5
                sudo git commit -m "Commit for new changes"
                sleep 5
                sudo git pull origin main
                sleep 10
                sudo npm run build
                sleep 20
                sudo SEARCHABLE=${{ secrets.SEARCHABLE }} API_PAGE_URL=${{ secrets.API_PAGE_URL }} NEXT_PUBLIC_URL=${{ secrets.NEXT_PUBLIC_URL }} pm2 restart new-estate-nuanu --update-env
                sudo systemctl restart nginx
            else 
                echo "No Update Found"
                sudo git pull origin main
                sleep 10
            fi
            
